/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssessmentInput = IDL.Record({
  'age' : IDL.Nat,
  'smoking' : IDL.Variant({
    'none' : IDL.Null,
    'current' : IDL.Null,
    'former' : IDL.Null,
  }),
  'symptomsFactor' : IDL.Record({
    'difficultySwallowing' : IDL.Bool,
    'bloodInSputum' : IDL.Bool,
    'cough' : IDL.Bool,
    'wheezing' : IDL.Bool,
    'shortnessOfBreath' : IDL.Bool,
    'unexplainedWeightLoss' : IDL.Bool,
    'stridor' : IDL.Bool,
  }),
  'gender' : IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
});
export const RiskFactor = IDL.Record({
  'detail' : IDL.Text,
  'category' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'moderate' : IDL.Null,
});
export const AssessmentResult = IDL.Record({
  'explanation' : IDL.Vec(RiskFactor),
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'calculateRisk' : IDL.Func([AssessmentInput], [AssessmentResult], []),
  'riskLevelToText' : IDL.Func([RiskLevel], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssessmentInput = IDL.Record({
    'age' : IDL.Nat,
    'smoking' : IDL.Variant({
      'none' : IDL.Null,
      'current' : IDL.Null,
      'former' : IDL.Null,
    }),
    'symptomsFactor' : IDL.Record({
      'difficultySwallowing' : IDL.Bool,
      'bloodInSputum' : IDL.Bool,
      'cough' : IDL.Bool,
      'wheezing' : IDL.Bool,
      'shortnessOfBreath' : IDL.Bool,
      'unexplainedWeightLoss' : IDL.Bool,
      'stridor' : IDL.Bool,
    }),
    'gender' : IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
  });
  const RiskFactor = IDL.Record({ 'detail' : IDL.Text, 'category' : IDL.Text });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const AssessmentResult = IDL.Record({
    'explanation' : IDL.Vec(RiskFactor),
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'calculateRisk' : IDL.Func([AssessmentInput], [AssessmentResult], []),
    'riskLevelToText' : IDL.Func([RiskLevel], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };