/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssessmentInput {
  'age' : bigint,
  'bloodPressure' : [] | [
    { 'value' : bigint, 'pressureType' : BloodPressureType }
  ],
  'smoking' : { 'none' : null } |
    { 'current' : null } |
    { 'former' : null },
  'symptomsFactor' : {
    'difficultySwallowing' : boolean,
    'bloodInSputum' : boolean,
    'cough' : boolean,
    'wheezing' : boolean,
    'shortnessOfBreath' : boolean,
    'unexplained_weight_loss' : boolean,
    'stridor' : boolean,
  },
  'gender' : { 'female' : null } |
    { 'male' : null },
}
export interface AssessmentResult {
  'explanation' : Array<RiskFactor>,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
}
export type BloodPressureType = { 'systolic' : null } |
  { 'diastolic' : null } |
  { 'meanArterialPressure' : null };
export interface RiskFactor { 'detail' : string, 'category' : string }
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'moderate' : null };
export interface _SERVICE {
  'calculateRisk' : ActorMethod<[AssessmentInput], AssessmentResult>,
  'riskLevelToText' : ActorMethod<[RiskLevel], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];