/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssessmentInput {
  'age' : bigint,
  'socialFactors' : SocialFactors,
  'respiratorySymptoms' : SymptomRespiratory,
  'hypertension' : boolean,
  'generalSymptoms' : SymptomGeneral,
  'gender' : Gender,
  'diabetes' : boolean,
}
export interface AssessmentResult {
  'suggestedTests' : string,
  'clinicalImpression' : string,
  'explanation' : string,
  'lifestyleRecommendations' : string,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
}
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface Patient {
  'id' : PatientId,
  'registeredBy' : UserId,
  'lastName' : string,
  'firstName' : string,
}
export type PatientId = bigint;
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'moderate' : null };
export interface SocialFactors {
  'alcohol' : boolean,
  'diet' : string,
  'exercise' : string,
  'smoking' : boolean,
}
export interface SymptomGeneral {
  'pain' : string,
  'weightLoss' : [] | [{ 'hasWeightLoss' : boolean, 'severity' : string }],
}
export interface SymptomRespiratory {
  'cough' : { 'individual' : null } |
    { 'family' : null },
  'wheezing' : { 'individual' : null } |
    { 'family' : null },
  'shortnessOfBreath' : { 'individual' : null } |
    { 'family' : null },
  'stridorSeverity' : { 'individual' : null } |
    { 'family' : null },
  'hemoptysis' : { 'individual' : null } |
    { 'family' : null },
  'coughFrequency' : [] | [bigint],
}
export type UserId = Principal;
export interface _SERVICE {
  'calculateRisk' : ActorMethod<[PatientId, AssessmentInput], AssessmentResult>,
  'getPatient' : ActorMethod<[bigint], Patient>,
  'registerPatient' : ActorMethod<[string, string], PatientId>,
  'riskLevelToText' : ActorMethod<[RiskLevel], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];