/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AssessmentInput {
    age: bigint;
    smoking: Variant_none_current_former;
    symptomsFactor: {
        difficultySwallowing: boolean;
        bloodInSputum: boolean;
        cough: boolean;
        wheezing: boolean;
        shortnessOfBreath: boolean;
        unexplainedWeightLoss: boolean;
        stridor: boolean;
    };
    gender: Variant_female_male;
}
export interface RiskFactor {
    detail: string;
    category: string;
}
export interface AssessmentResult {
    explanation: Array<RiskFactor>;
    riskLevel: RiskLevel;
    riskScore: bigint;
}
export enum RiskLevel {
    low = "low",
    high = "high",
    moderate = "moderate"
}
export enum Variant_female_male {
    female = "female",
    male = "male"
}
export enum Variant_none_current_former {
    none = "none",
    current = "current",
    former = "former"
}
export interface backendInterface {
    calculateRisk(assessmentInput: AssessmentInput): Promise<AssessmentResult>;
    riskLevelToText(level: RiskLevel): Promise<string>;
}
import type { AssessmentInput as _AssessmentInput, AssessmentResult as _AssessmentResult, RiskFactor as _RiskFactor, RiskLevel as _RiskLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateRisk(arg0: AssessmentInput): Promise<AssessmentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateRisk(to_candid_AssessmentInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AssessmentResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateRisk(to_candid_AssessmentInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AssessmentResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async riskLevelToText(arg0: RiskLevel): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.riskLevelToText(to_candid_RiskLevel_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.riskLevelToText(to_candid_RiskLevel_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AssessmentResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentResult): AssessmentResult {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    explanation: Array<_RiskFactor>;
    riskLevel: _RiskLevel;
    riskScore: bigint;
}): {
    explanation: Array<RiskFactor>;
    riskLevel: RiskLevel;
    riskScore: bigint;
} {
    return {
        explanation: value.explanation,
        riskLevel: from_candid_RiskLevel_n7(_uploadFile, _downloadFile, value.riskLevel),
        riskScore: value.riskScore
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "moderate" in value ? RiskLevel.moderate : value;
}
function to_candid_AssessmentInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentInput): _AssessmentInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    smoking: Variant_none_current_former;
    symptomsFactor: {
        difficultySwallowing: boolean;
        bloodInSputum: boolean;
        cough: boolean;
        wheezing: boolean;
        shortnessOfBreath: boolean;
        unexplainedWeightLoss: boolean;
        stridor: boolean;
    };
    gender: Variant_female_male;
}): {
    age: bigint;
    smoking: {
        none: null;
    } | {
        current: null;
    } | {
        former: null;
    };
    symptomsFactor: {
        difficultySwallowing: boolean;
        bloodInSputum: boolean;
        cough: boolean;
        wheezing: boolean;
        shortnessOfBreath: boolean;
        unexplainedWeightLoss: boolean;
        stridor: boolean;
    };
    gender: {
        female: null;
    } | {
        male: null;
    };
} {
    return {
        age: value.age,
        smoking: to_candid_variant_n3(_uploadFile, _downloadFile, value.smoking),
        symptomsFactor: value.symptomsFactor,
        gender: to_candid_variant_n4(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_none_current_former): {
    none: null;
} | {
    current: null;
} | {
    former: null;
} {
    return value == Variant_none_current_former.none ? {
        none: null
    } : value == Variant_none_current_former.current ? {
        current: null
    } : value == Variant_none_current_former.former ? {
        former: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_female_male): {
    female: null;
} | {
    male: null;
} {
    return value == Variant_female_male.female ? {
        female: null
    } : value == Variant_female_male.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
