/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface SymptomRespiratory {
    cough: Variant_individual_family;
    wheezing: Variant_individual_family;
    shortnessOfBreath: Variant_individual_family;
    stridorSeverity: Variant_individual_family;
    hemoptysis: Variant_individual_family;
    coughFrequency?: bigint;
}
export interface SocialFactors {
    alcohol: boolean;
    diet: string;
    exercise: string;
    smoking: boolean;
}
export interface AssessmentResult {
    suggestedTests: string;
    clinicalImpression: string;
    explanation: string;
    lifestyleRecommendations: string;
    riskLevel: RiskLevel;
    riskScore: bigint;
}
export interface AssessmentInput {
    age: bigint;
    socialFactors: SocialFactors;
    respiratorySymptoms: SymptomRespiratory;
    hypertension: boolean;
    generalSymptoms: SymptomGeneral;
    gender: Gender;
    diabetes: boolean;
}
export interface SymptomGeneral {
    pain: string;
    weightLoss?: {
        hasWeightLoss: boolean;
        severity: string;
    };
}
export type PatientId = bigint;
export interface Patient {
    id: PatientId;
    registeredBy: UserId;
    lastName: string;
    firstName: string;
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    moderate = "moderate"
}
export enum Variant_individual_family {
    individual = "individual",
    family = "family"
}
export interface backendInterface {
    calculateRisk(patientId: PatientId, assessmentInput: AssessmentInput): Promise<AssessmentResult>;
    getPatient(patientId: bigint): Promise<Patient>;
    registerPatient(firstName: string, lastName: string): Promise<PatientId>;
    riskLevelToText(level: RiskLevel): Promise<string>;
}
import type { AssessmentInput as _AssessmentInput, AssessmentResult as _AssessmentResult, Gender as _Gender, RiskLevel as _RiskLevel, SocialFactors as _SocialFactors, SymptomGeneral as _SymptomGeneral, SymptomRespiratory as _SymptomRespiratory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateRisk(arg0: PatientId, arg1: AssessmentInput): Promise<AssessmentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateRisk(arg0, to_candid_AssessmentInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AssessmentResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateRisk(arg0, to_candid_AssessmentInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AssessmentResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return result;
        }
    }
    async registerPatient(arg0: string, arg1: string): Promise<PatientId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPatient(arg0, arg1);
            return result;
        }
    }
    async riskLevelToText(arg0: RiskLevel): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.riskLevelToText(to_candid_RiskLevel_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.riskLevelToText(to_candid_RiskLevel_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AssessmentResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentResult): AssessmentResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suggestedTests: string;
    clinicalImpression: string;
    explanation: string;
    lifestyleRecommendations: string;
    riskLevel: _RiskLevel;
    riskScore: bigint;
}): {
    suggestedTests: string;
    clinicalImpression: string;
    explanation: string;
    lifestyleRecommendations: string;
    riskLevel: RiskLevel;
    riskScore: bigint;
} {
    return {
        suggestedTests: value.suggestedTests,
        clinicalImpression: value.clinicalImpression,
        explanation: value.explanation,
        lifestyleRecommendations: value.lifestyleRecommendations,
        riskLevel: from_candid_RiskLevel_n12(_uploadFile, _downloadFile, value.riskLevel),
        riskScore: value.riskScore
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "moderate" in value ? RiskLevel.moderate : value;
}
function to_candid_AssessmentInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentInput): _AssessmentInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_SymptomGeneral_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SymptomGeneral): _SymptomGeneral {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SymptomRespiratory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SymptomRespiratory): _SymptomRespiratory {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    socialFactors: SocialFactors;
    respiratorySymptoms: SymptomRespiratory;
    hypertension: boolean;
    generalSymptoms: SymptomGeneral;
    gender: Gender;
    diabetes: boolean;
}): {
    age: bigint;
    socialFactors: _SocialFactors;
    respiratorySymptoms: _SymptomRespiratory;
    hypertension: boolean;
    generalSymptoms: _SymptomGeneral;
    gender: _Gender;
    diabetes: boolean;
} {
    return {
        age: value.age,
        socialFactors: value.socialFactors,
        respiratorySymptoms: to_candid_SymptomRespiratory_n3(_uploadFile, _downloadFile, value.respiratorySymptoms),
        hypertension: value.hypertension,
        generalSymptoms: to_candid_SymptomGeneral_n6(_uploadFile, _downloadFile, value.generalSymptoms),
        gender: to_candid_Gender_n8(_uploadFile, _downloadFile, value.gender),
        diabetes: value.diabetes
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cough: Variant_individual_family;
    wheezing: Variant_individual_family;
    shortnessOfBreath: Variant_individual_family;
    stridorSeverity: Variant_individual_family;
    hemoptysis: Variant_individual_family;
    coughFrequency?: bigint;
}): {
    cough: {
        individual: null;
    } | {
        family: null;
    };
    wheezing: {
        individual: null;
    } | {
        family: null;
    };
    shortnessOfBreath: {
        individual: null;
    } | {
        family: null;
    };
    stridorSeverity: {
        individual: null;
    } | {
        family: null;
    };
    hemoptysis: {
        individual: null;
    } | {
        family: null;
    };
    coughFrequency: [] | [bigint];
} {
    return {
        cough: to_candid_variant_n5(_uploadFile, _downloadFile, value.cough),
        wheezing: to_candid_variant_n5(_uploadFile, _downloadFile, value.wheezing),
        shortnessOfBreath: to_candid_variant_n5(_uploadFile, _downloadFile, value.shortnessOfBreath),
        stridorSeverity: to_candid_variant_n5(_uploadFile, _downloadFile, value.stridorSeverity),
        hemoptysis: to_candid_variant_n5(_uploadFile, _downloadFile, value.hemoptysis),
        coughFrequency: value.coughFrequency ? candid_some(value.coughFrequency) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pain: string;
    weightLoss?: {
        hasWeightLoss: boolean;
        severity: string;
    };
}): {
    pain: string;
    weightLoss: [] | [{
            hasWeightLoss: boolean;
            severity: string;
        }];
} {
    return {
        pain: value.pain,
        weightLoss: value.weightLoss ? candid_some(value.weightLoss) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_individual_family): {
    individual: null;
} | {
    family: null;
} {
    return value == Variant_individual_family.individual ? {
        individual: null
    } : value == Variant_individual_family.family ? {
        family: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
